export  const ListAnimes=[
    {
        id:"1",
        statuss:"đã kết thúc",
        content:"Nội dung kể về thiếu niên Lôi Vô Kiệt (Ngao Thụy Bằng) “chân ướt chân ráo” vừa bước vào chốn giang hồ. Y tình cờ quen biết hoàng tử ẩn dật Tiêu Sắt (Lý Hoành Nghị) và từ đó, hai người đồng hành xông pha giang hồ, bị cuốn vào triều đình phân tranh, hỗ trợ lẫn nhau trong vô vàn âm mưu hiểm kế, sau cùng vang danh thiên hạ.",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"thiếu niên ca hành",
        img:"https://tse3.mm.bing.net/th?id=OIP.-caswCPW2LP8DHqZsYs9rgHaEK&pid=Api&P=0&h=220",
       
    },
    {
        id:"2",
        statuss:"đã kết thúc",
        content:"Drama Trường Tương Tư (长相思 | Lost You Forever) là bộ phim cổ trang thần thoại chuyển thể từ tiểu thuyết ngôn tình cùng tên của Đồng Hoa. Phim do Tencent Penguin Pictures phối hợp với Tinh Liên sản xuất. Đạo diễn Tần Trăn, Dương Hoan, biên kịch là tác giả nguyên tác Đồng Hoa. Các diễn viên chính: Dương Tử, Trương Vãn Ý, Đặng Vi, Đại Lộ Oa, Vương Hoằng Nghị, Vương Chân, Đàn Kiện Thứ.",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"trường tương phủ",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-V56wPwA_IVQ/XsFHitWDORI/AAAAAAAAHG8/BlKUkf29FBIxtJJJpDzKa4agIBr2OMc0QCLcBGAsYHQ/s1600/321324654.jpg",
      
    },
    {
        id:"3",
        statuss:"đã kết thúc",
        content:"Nguyệt thượng trọng hỏa (月上重火| And The Winner Is Love) là bộ phim ngôn tình cổ trang chuyển thể từ tiểu thuyết cùng tên của Quân Tử Dĩ Trạch, thuộc thể loại võ hiệp. Phim do Ninh Ba Ảnh Thị phối hợp với Bắc Kinh hoàn mỹ sản xuất, đạo diễn Hà Chú Bồi. La Vân Hi và Trần Ngọc Kỳ diễn chính",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"nguyệt thượng trọng hỏa",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://4.bp.blogspot.com/-4poTDA3-XKE/XtCHxSQTnUI/AAAAAAAAHNo/7uPq78agAv872aNJKEnIyCDWpjT7HhtJgCLcBGAsYHQ/s1600/124125.jpg",
       
    },
    {
        id:"4",
        statuss:"đã kết thúc",
        content:"Nội dung Em Là Định Mệnh Đời Anh xoay quanh câu chuyện tình yêu của cô gái trẻ ngây thơ, dễ thương tên Trần Gia Hân và doanh nhân tài giỏi, người thừa kế tập đoàn Vương Tích Dực. Cả hai tình cờ gặp gỡ trên một con tàu, vì hiểu nhầm mà xảy ra “tình một đêm”.",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"em là định mệnh đời anh",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://2.bp.blogspot.com/-fjRi8kSMj4k/Xt-Stma_WxI/AAAAAAAAHWY/NR2hobBHdzwLe7XEvYPMj0e4FUGOqC24gCLcBGAsYHQ/s1600/24sdg.jpg",
        
    },
    {
        id:"5",
        statuss:"đã kết thúc",
        content:"Trọng Tử trong sáng, lương thiện. Nhưng lại là con gái của Ma Tôn nghịch luân, được một vị thần tiên cứu giúp. Từ đó, nàng đã quyết định lên Nam Hoa để tu tiên học đạo. Đáng tiếc, cô bị chặn ngoài cửa bởi vì các vị tôn giả ở Nam Hoa đều cảm nhận được sát khí trời sinh của nàng.",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"trùng tử",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://lh3.googleusercontent.com/-HSC2jWxj_Us/Y_TVano8QhI/AAAAAAAAA70/3A2q9Pa1vD0WvEVH4yEN_huc1IAq17F1ACNcBGAsYHQ/s500/trung-tu-tvphim.us.jpg",
       
    },
    {
        id:"6",
        statuss:"đã kết thúc",
        content:"Năm năm sau sự sụp đổ của Đế chế Thiên hà[1] một thợ săn tiền thưởng Mandalore tới gặp Greef Karga. Anh chấp nhận một nhiệm vụ tuyệt mật tại hành tinh tiền đồn Nevarro từ một khách hàng có quan hệ với Đế chế, chỉ dẫn cho anh cách lần dấu và bắt giữ một đối tượng 50 tuổi. Tuy Khách hàng không quan tâm đến sự sống còn của đối tượng, Tiến sĩ Pershing khăng khăng rằng nó phải còn sống. Người Mandalore được đặt cọc một thỏi sắt Beskar duy nhất, thứ kim loại rất quý đối với người của anh. Anh tới một căn cứ Mandalore nhỏ, nơi anh được rèn cho một cái giáp vai mới. Tới hành tinh nơi đối tượng được nhìn thấy lần cuối, người Mandalore được hỗ trợ bởi một nông dân ẩm tên Kuiil. Mệt mỏi về loạn lạc do bọn thợ săn tiền thưởng gây ra tại nơi đây, Kuiil đưa anh tới địa điểm và rời đi. Đi vào sảo huyệt được phòng vệ cẩn mật, người Mandalore phải hợp sức với con droid sát thủ IG-11 đế tiêu diệt khu trại và bắt được đối tượng– một đứa trẻ thuộc giống loài Yoda. IG-11 định thủ tiêu đứa trẻ, người Mandalore bắn con người máy và mang đứa trẻ đi còn sống.",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"người Mandorian",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-9q1boI4QEH0/YFDH1ThV7TI/AAAAAAAADeo/3NoSnbE8xBMpXn25nlsT0D_ugZxgwu56QCLcBGAsYHQ/w270-h400/the-mandalorian-season-2-poster-692x1024.jpeg",
        
    },
    {
        id:"7",
        statuss:"đã kết thúc", 
        content:"",
        year:"2023",
        type:"Phim Hành Động, Phim Kinh Dị", 
        time:" 122 phút",    
        paramater:"ack Champion, Jasmin Savoy Brown, Melissa Barrera",
        country:"Phim Mỹ",
        times:"1 tập",
        director:"Matt Bettinelli-Olpin",
        titleExtra:"",    
        title:"Tiếng thét 6",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-SUpBeDLON6w/ZRrWnFCkhwI/AAAAAAAAGcE/1547zNu9guQDQRl98yXcLCQvESTq016tACNcBGAsYHQ/s16000/81zPtUUduML._AC_UF1000%252C1000_QL80_.jpg",
        
    },
    {
        id:"8",
        statuss:"đã kết thúc", 
        content:"Tiếng Thét 6 , Scream VI (Vietsub Thuyết Minh)  Một năm sau sự kiện Vụ án giết người Woodsboro 2022, tại thành phố New York, giáo sư điện ảnh tại Đại học Blackmore, Laura Crane, đang đợi hẹn hò của mình ở một quán bar. Cô nhận được một tin nhắn từ người hẹn hò của mình cho biết anh ta lạc đường và yêu cầu được gọi điện. Cô đồng ý và hai người nói chuyện qua điện thoại, với người hẹn hò tiết lộ rằng anh ta đến nhầm nơi nhưng đang trên đường đến. Laura ra ngoài đợi anh ta và anh ta cho biết anh đang đi xuống hẻm và có thể nhìn thấy cô. Laura trở nên lo lắng khi người hẹn hò tiết lộ rằng anh ta bị theo dõi bởi một kẻ cầm dao và cô chạy xuống hẻm để gặp anh ta nhưng lại bị Ghostface giết chết. Kẻ giết người được tiết lộ là học sinh của cô, Jason Carvey. Sau đó, anh ta bỏ xác nạn nhân và trở về phòng ký túc xá của mình, nơi tiết lộ rằng anh ta và bạn cùng phòng của mình, Greg, là fan của Richie Kirsch và muốn hoàn thành bộ phim anh ta đang làm. Jason nhận cuộc gọi từ 'Greg' đang sử dụng giọng Ghostface và anh ta chơi một trò chơi Hot and Cold với Jason, dẫn dắt anh ta đến tủ lạnh nơi xác Greg bị tàn phá bên trong. Ghostface, đang đeo mặt nạ của Richie, tấn công Jason. Jason đặt câu hỏi cho kẻ giết người về bộ phim của họ và Ghostface trả lời.",
        year:"2023",
        type:"phim cổ trang ,phim hành ddoogj ", 
        time:"148 phút",   
        paramater:"layout, passenger",
        country:"trung quốcphim pháp",
        times:"1 tập",
        director:"ô nhĩ thiện luffy,nmai,ussop",
        titleExtra:"CREATION OF THE GODS I: THE WHITE STORM 3: HEAVEN OR HELL (2023)KINGDOM OF STORMS (2023)",     
        title:"Phong thần 1:Tam Bộ Khúc",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-XH9Y3cKys0Y/ZRhplvcEqeI/AAAAAAAAGbg/5wjqXJkc_lE3KktKfym13dHRJuc2SjzXQCNcBGAsYHQ/s16000/image.jpg",
        
    },
    {
        id:"9",
        statuss:"đã kết thúc", 
        content:"Hưởng xái từ người mẹ chuyên gia, cậu chàng Otis nhút nhát khá rành rọt về mấy chuyện. Thế là cô bạn nổi loạn Maeve bèn rủ cậu mở phòng khám tư vấn cho chúng bạn.",
        year:"2023",
        type:"phim hài , phim tâm lý", 
        time:" 8 tập",     
        paramater:": Asa Butterfield, Gillian Anderson, Ncuti Gatwa",
        country:"phim mỹ",
        times:"1 tập",
        director:" Laurie Nunn",
        titleExtra:"SEX EDUCATION SEASON 4 (2023)",    
         title:"Giáo dục giới tính màu 4",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://lh3.googleusercontent.com/-qjTLI5lldHQ/ZQw6lucY4xI/AAAAAAAAE7g/1Mz_YNyOdVIA0usThUbb2IK-OPQfuTDPgCNcBGAsYHQ/s520/Sex_Education_Final_Season_Poster.webp",
        
    },
    {
        id:"10",
        statuss:"đã kết thúc",
        content:"Tại một thành phố hư cấu Jungjin, một nhóm người săn quỷ được gọi “Bộ đếm”, họ làm nhiệm vụ tìm kiếm và trục xuất những linh hồn ác quỷ thoát khỏi thế giới bên kia để có được sự bất tử. Những linh hồn ác quỷ tìm kiếm và chiếm hữu vật chủ của mình là những người địa phương, những tên sát nhân hoặc những người bạo lực muốn giết người, khuyến khích vật chủ giết người và hấp thụ linh hồn của nạn nhân. Những người có thể tham gia hội săn quỷ là những người đã từng hôn mê, họ đứng giữa ranh giới sự sống và cái chết, họ liên kết với linh hồn cộng sự từ Yung, chiếm hữu và mang lại cho họ cơ thể và ý thức hoàn toàn khỏe mạnh cùng với sức mạnh siêu phàm và khả năng siêu nhiên. 3 thành viên của nhóm “Bộ đếm” là Ga Mo-tak (Yoo Jun-sang), Do Ha-na (Kim Se-jeong) và Chu Mae-ok (Yeom Hye-ran). Họ cùng nhau làm việc tại quán Mì Của Chị, và cũng là nơi ẩn náu của họ.",
        year:"2022",
        type:": Phim Hành Động, Phim Phiêu Lưu, Phim Tình Cảm",
        time:"122 phút",
        paramater:" Ahn Suk Hwan, Cho Byeong Kyu, Kim Se-Jeong, Yeom Hye-ran, Yoo Joon Sang",
        country:"phim hàn quốc",
        times:"1 tập",
        director:"Yoo Seon Dong",
        titleExtra:"THE UNCANNY COUNTER S02 (202)",
        title:"Nghệ thuật săn quỷ và nấu mì",
         img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://lh3.googleusercontent.com/-SOttn7Sxjhg/ZMcpwgHAh-I/AAAAAAAAEsY/rVro2xqKNiEz4Q254h5-LQi8gUYLS-KYgCNcBGAsYHQ/s520/adasdasd.jpg",
        
     },
    {
        id:"11",
        statuss:"đã kết thúc",
        content:"Tóm tắt nội dung phim Bài Ca Của Lưỡi Kiếm Lấy bối cảnh thời Nhật Bản chiếm đóng Hàn Quốc vào năm 1920, Song of The Bandits kể câu chuyện về một cuộc phiêu lưu đầy hấp dẫn ở một khu vực vô luật pháp tên là Gando. Nơi mọi người chiến đấu để bảo vệ ngôi nhà và những người thân yêu của mình.",
        year:"2023",
        type:"Phim Hành Động",
        time:"132 phút",
        paramater:"Kim Nam Gil, Seo Hyun, Yu Jae Myung",
        country:"hàn quốc",
        director:": Han Jung Hoon",
        titleExtra:"SONG OF THE BANDITS (2023)",
        title:"Bài ca của lười kiếm",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://lh3.googleusercontent.com/-KQu0HUOrUHg/ZQ1bFyC0hAI/AAAAAAAAE7s/lzVrARTKtGAkPUn5p16d-D0wQpMC5RwQwCNcBGAsYHQ/s520/Song_of_the_Bandits-p2.jpg",
        
    },
    {
        id:"11",
        statuss:"đã kết thúc",
        content:"Năm 1998, tàu vũ trụ Atlantic nổ tung trong không gian sau khi va chạm với hàng nghìn thiên thạch nhỏ trong lúc người ta đang tiến hành sửa chữa. Ngay sau đó, một khu vực nằm giữa Phần Lan và tiểu bang South Carolina (Mỹ) cũng hứng chịu sự tấn công của thiên thạch. Nhiều tòa nhà cao tầng và danh lam thắng cảnh ở Thành phố New York bị thiên thạch phá hủy, trong đó có Trung tâm Thương mại Thế giới.",
        year:"2023",
        type:"phim hành ddoognj , phim phiêu lưu",
        time:" 90 phút",
        paramater:"thức",
        country:"phim mỹ",
        times:"1 tập",
        director:"",
        titleExtra:"SPY KIDS: ARMAGEDDON (2023)",
        title:"Ngày tận thế",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://lh3.googleusercontent.com/-q2IohWSVDgk/ZQ1025zVldI/AAAAAAAAE74/8X6EhjJqbDwqtXS3V8StopvRfFjUqqogwCNcBGAsYHQ/s520/57t6o5emdopdpQ76LJWexBOa6Y2.jpg",
        
    },
    {
        id:"12",
        statuss:"đã kết thúc",
        content:"Nội dung chính phim Đồng Thoại Độc Nhất Lăng Siêu và Tiêu Thố cùng nhau lớn lên từ khi còn bé, mỗi người một tính cách riêng nhưng khi ở bên nhau, họ hòa hợp một cách đặc biệt. Tiêu Thố dễ thương, chân thành và có phần ngốc nghếch, trong khi Lăng Siêu lạnh lùng, ít nói, nhưng rất thông minh.",
        year:"2023",
        type:"phim tâm lí , tình cảm",
        time:"24 phút",
        paramater:"Hách Châu Vũ, Hùng Áo Bác, Lữ Chiêu, Trương Miểu Di, Văn Tuấn Huy",
        country:"phim trung quốc",
        times:"1 tập",
        director:"cung vũ thi",
        titleExtra:"EXCLUSIVE FAIRYTALE (2023)",
        title:"Đồng thoại độc nhất",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://lh3.googleusercontent.com/-T9DClhZgKnI/ZN78Hz6zR2I/AAAAAAAABgY/d1XxEkyHC9QEPTMKPfPhZX0ZSP8m1owAgCNcBGAsYHQ/s570/dong-thoai-doc-nhat.jpg.png",
        
    },
    {
        id:"13",
        statuss:"đã kết thúc",
        content:"Phim chính thức trình chiếu tại 265 rạp phim ở Hàn Quốc vào ngày 1 tháng 4 năm 2005. Ngọt đắng cuộc đời đã thu hút 1,112,950 lượt khán giả tới rạp trên toàn quốc.[2][3] Tác phẩm cũng được công chiếu tại Liên hoan phim Cannes 2005.[4] Bản dựng đạo diễn có thời lượng dài hơn 30 giây so với phiên bản chiếu rạp của phim với vài cảnh quay, đoạn nhạc được sắp xếp lại và một số cảnh bổ sung, cũng được phát hành ngay sau đó. Ngọt đắng cuộc đời có một phiên bản làm lại không chính thức do Ấn Độ sản xuất năm 2017 mang tên Awarapan.",
        year:"2023",
        type:"phim tình cảm ",
        time:"124 phút",
        paramater:"hamter",
        country:"phim nhật bản ",
        times:"1 tập",
        director:"alexander thức",
        titleExtra:"",
        title:"Ngọt đắng cuộc đời ",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-58iTAEYRWmc/ZQa805uYGXI/AAAAAAAAGaQ/exS6Jb38rKILqUuUeRvj6zApPKf2UmCPgCNcBGAsYHQ/s16000/A_Bittersweet_Life_Poster.jpg",
        
    },
    {
        id:"14",
        statuss:"đã kết thúc",
        content:"Bộ phim {Bão Trắng 3: Thiên Đàng Hay Địa Ngục} mở ra một thế giới đầy ám ảnh và căng thẳng, xoay quanh hai nhân vật chính là Âu Chí Viễn và Trương Kiến Hành, cả hai là những cảnh sát chìm tài năng hoạt động trong cuộc chiến chống lại một băng đảng ma túy quyền lực, dưới sự lãnh đạo của tên trùm Khang Tố Sai, ngự trị tại thủ đô kinh tế Hongkong.",
        year:"2021",
        type:"phim hành đọngo ",
        time:"50 phút",
        paramater:"ten hag",
        country:" phim anh",
        times:"1 tập",
        director:"ronando",
        titleExtra:"macus alonso",
        title:"thiên đàng hay địa ngục",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-vM8n8DsgYCQ/ZP28hL0ddbI/AAAAAAAAGZ8/iLMIkVIBM4wackDxEBj-LEd54o10YB3oQCNcBGAsYHQ/s16000/official_posterfb.jpg",
        
    },
    {
        id:"15",
        statuss:"đã kết thúc",
        content:"Luyện Khí Mười Vạn Năm là một bộ phim hoạt hình Trung Quốc đầy kịch tính và hấp dẫn, mang đến cho khán giả một cuộc phiêu lưu đáng nhớ thông qua câu chuyện của nhân vật chính Từ Dương - một đệ tử khai sơn của Thiên Lam Tông. Từ Dương, với mong muốn đột phá tu vi và phi thăng sớm, luôn cố gắng luyện tập và rèn luyện kỹ năng.",
        year:"2019",
        type:"phim hoạt hình",
        time:"24 phút",
        paramater:"châu tinh trì",
        country:"phm nhật bản ",
        times:"1 tập",
        director:"alex firguson",
        titleExtra:"thousen",
        title:"Luyện Khí Mười Vạn Năm",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-6iBM3JzPtHM/ZMiC9KxiQxI/AAAAAAAAGQ8/kkn7mDeRRq4n-0K-T_ZsaY64sRsEVmYUACNcBGAsYHQ/s16000/luyenKhi.jpg",
        
    },
    {
        id:"16",
        statuss:"đã kết thúc",
        content:"Câu chuyện bắt đầu về giấc mơ của Tư Mã Ý, trong mơ ông thấy mình đang thao túng hoàng đế trị vì thiên hạ thì xuất hiện quái vật một mình đấu vạn người xông vào hành thích ông... Giấc mơ báo trước tương lai.Liêu Nguyên Hỏa là thủ lĩnh của Tàn binh, một nhóm sát thủ hành động theo lệnh của Tư Mã Ý đã hành thích Hứa Lâm người được xem là Trí trùm thiên hạ",
        year:"2018",
        type:"phim đối kháng",
        time:"39 phút",
        paramater:"layout, passenger",
        country:"phim trung quốcphim pháp",
        times:"1 tập",
        director:"paul pogbaluffy,nmai,ussop",
        titleExtra:"free fireTHE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Hỏa Phụng Liêu Nguyên",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-DZmzpQAB-Pw/ZMp3uWBuSvI/AAAAAAAAGRY/inBmRRZTDswYA8wwnmqVvqKRB09_l5shwCNcBGAsYHQ/s16000/X1000_.jpg",
        
    },
    {
        id:"16",
        statuss:"đã kết thúc",
        content:"Trong một lần chiến đấu, đệ nhất phế vật Ngô Nhiên bị thương nặng, ngẫu nhiên kích hoạt càn khôn chí bảo hệ thống Thánh Hồ Đầu Tử (xúc xắc), giành được kỹ năng Thần Đầu kỳ dị cổ quái, giải cứu tiểu sư thúc, đánh bại nữ tu tiên giả Nghê Sa. Sau đó cô ta ái mộ hắn, hơn nữa còn muốn bắt Ngô Nhiên về tông môn. Nữ tu tiên giả Nghê Sa cùng Bạch Long Vương tấn công thành trì địa cầu, muốn đạt được càn khôn chí bảo. Sau cùng Ngô Nhiên đánh bại Nghê Sa, bảo vệ được thành trì địa cầu.",
        year:"2014",
        type:"phim trung quốc",
        time:"35 phút",
        paramater:" verati,leao",
        country:"phim anh",
        times:"1 tập",
        director:"konate",
        titleExtra:"focus-opensocial.",
        title:"Nghịch Thiên Chiến Kỉ",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-0O19vfBTMR4/ZEik-XZJQ6I/AAAAAAAAEEU/dc6kroi-lwM-slPiAm-2UVc1SLXEFlUowCNcBGAsYHQ/s520/nghich-thien-chien-ky-2023-tvphim.jpg",
        
    },
    {
        id:"17",
        statuss:"đã kết thúc",
        content:", nội dung phim Xóa Bỏ Đây là loạt phim truyền hình giật gân sẽ bật ‘chế độ tối’ cho những người có bí mật. Một chiếc điện thoại di động có thể khiến mọi người biến mất, và khi nó rơi vào tay những người đang có các mối quan hệ phức tạp và che giấu những bí mật, họ sẽ phải quyết định xem họ muốn xóa ai khỏi cuộc đời mình.",
        year:"2015",
        type:"phim đấu tường",
        time:"54 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Xóa Bỏ",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://lh3.googleusercontent.com/-miWfwNJVw-Q/ZJ0IeLYZmXI/AAAAAAAAEhA/b04fe9l0yUgGo1ty1AhY4cubSTDK8ADlACNcBGAsYHQ/s520/xb.jpg",
        
    },
    {
        id:"17",
        statuss:"đã kết thúc",
        content:"Sau khi vua Edward qua đời, Uhtred xứ Bebbanburg và các đồng đội phiêu lưu qua một vương quốc bị chia cắt với hi vọng cuối cùng sẽ thống nhất nước Anh.",
        year:"2015",
        type:"phim đấu tường",
        time:"54 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Cái Chết Của Bảy Vị Vua",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-q3qb6f7InoE/ZRB5MpCvc3I/AAAAAAAAGbE/6J5iv6mL2Ng81yzL8k_5DYR6APJGa7t8wCNcBGAsYHQ/s16000/aaa.jpg",
        
    },
    {
        id:"18",
        statuss:"đã kết thúc",
        content:"Phim Âm Mưu Của Quỷ - The Devil Conspiracy: thuộc thể loại kinh dị Mỹ do Nathan Frankowski làm đạo diễn kết hợp cùng các diễn viên tham gia: Alice Orr-Ewing, Joe Doyle, Eveline Hal, l Peter Mensah, Joe Anderson, Spencer Wilding, Brian Caspe, James Faulkner,...Nội dung phim Âm Mưu Của Quỷ - The Devil Conspiracy xoay quanh sự việc 1 tập đoàn công nghệ lớn mạnh đã tạo ra công nghệ vĩ đại có thể nhân bản những người có sức ảnh hưởng lớn chỉ bằng vài đoạn DNA.",
        year:"2015",
        type:"phim đấu tường",
        time:"54 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Âm mưu của quỷ ",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-IUzaGNvqnbY/ZQb49q3uCgI/AAAAAAAAGaY/nx9QeyJEzvcw5e-V0O3TtJXT9DP9o3yAgCNcBGAsYHQ/s16000/dea.jpg",
        
    },
    {
        id:"19",
        statuss:"đã kết thúc",
        content:"Two New Orleans detectives become embroiled in a centuries-long feud between two secretive factions of vampires while investigating a runaway child's case. Torn between their everyday lives and the dangerous lure of immortality, the detectives must race to destroy the evil Moldero clan.",
        year:"2015",
        type:"phim đấu tường",
        time:"54 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Truyền Nhân Ma Cà Rồng",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-QQF57aQrW_8/ZODZNXEEh_I/AAAAAAAAGXQ/0UE2VxXnHbgZMqef86XeU5Y9ehYJ5MWmACNcBGAsYHQ/s16000/Dampyr_film_poster.jpg",
        
    },
    {
        id:"20",
        statuss:"đã kết thúc",
        content:"Điệp Vụ Đoạt Hồn kể về một nhà thầu quân sự mạnh mẽ trong nhiệm vụ tìm kiếm một vũ khí nguy hiểm biến những người thông thường thành những tên sát nhân vô tâm. Nhưng đoán xem? Mọi thứ bất ngờ thay đổi khi chính người anh em của anh ta trở thành nạn nhân của vũ khí chết người này!",
        year:"2015",
        type:"phim đấu tường",
        time:"54 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Điệp vụ Đoạt Hồn",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/-TK_K4WYgJBg/ZOuhE6dQAsI/AAAAAAAAGYA/NWMhnUAaU2EkyU3wQZp4qUJHU_4gG_CZwCNcBGAsYHQ/s16000/p25270455_v_v9_ac.jpg",
        
    },
    {
        id:"21",
        statuss:"đã kết thúc",
        content:"Một nhân viên cứu hộ tên là Jonas Taylor đang cố gắng giải cứu một số nhà khoa học bị mắc kẹt trong một chiếc tàu ngầm hạt nhân bị hư hại khi anh thấy thân tàu bị đâm phải bởi một sinh vật khổng lồ. Hai người bạn thân của anh bị mắc kẹt trong cửa sập, Taylor buộc phải bỏ chạy vì nhận ra rằng cố gắng giải cứu họ sẽ khiến tất cả mọi người thiệt mạng, khiến anh buộc phải ngắt kết nối cửa với con tàu. Một lúc sau, chiếc tàu ngầm nổ tung. Câu chuyện của Taylor kể lại bị bác bỏ bởi bác sĩ Heller, người cho rằng Taylor là kẻ hèn nhát và bị tâm thần. Năm năm sau, tỷ phú Jack Morris gặp Tiến sĩ Trương Mẫn Uy tại một trạm nghiên cứu dưới nước trị giá 1,3 tỷ USD mang tên Mana One mà Morris đã đầu tư xây dựng. Trương và con gái ông, Tố Âm, một nhà hải dương học, giám sát một nhiệm vụ khám phá phần sâu hơn của Rãnh Mariana, bị che giấu bởi một dòng hydro sulfide đục ngầu. Một chiếc tàu lặn được cử xuống đáy biển, nó được điều khiển bởi Lori - vợ cũ của Taylor, cùng với các nhà khoa học DJ, Toshi và 'The Wall'. Suy luận của họ đã đúng khi họ khám phá ra vô số loài động thực vật chưa từng phát hiện bên dưới lớp thermocline. Một sinh vật khổng lồ va chạm với chiếc tàu lặn khiến nó mất liên lạc với trạm Mana One.",
        year:"2015",
        type:"phim đấu tường",
        time:"54 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Cá mập bạo chúa 2",
        img:"https://mp-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&refresh=604800&url=https://1.bp.blogspot.com/--sAxSkt0ZWg/ZPFDo-hehXI/AAAAAAAAGYc/ntztD7XMBSI242no8D5nVth99-svHBv2wCNcBGAsYHQ/s16000/output_image.png",
        
    },
    {
        id:"22",
        statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"đấu la đại lục",
        img:"https://tse1.mm.bing.net/th?id=OIP.4x9lZaZT3u0_HG-MQbu8UAAAAA&pid=Api&P=0&h=220",
        
    },
    {
        id:"23",
 statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"cái chết của bảy vị vua",
        img:"https://tse3.mm.bing.net/th?id=OIP.yEY-ctbA_tXPzTsH4e0HJQHaDq&pid=Api&P=0&h=220",
        
    },
    {
        id:"24",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"khắc tinh của quỷ",
        img:"https://tse1.mm.bing.net/th?id=OIP.cOmB59P-FPkOs86yXAHorwHaEK&pid=Api&P=0&h=220",
        
    },
    {
        id:"25",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"âm mưu của quỷ",
        img:"https://tse2.mm.bing.net/th?id=OIP.sImIYMKglQ5P30sn2NIS9gHaEW&pid=Api&P=0&h=220",
        
    },
    {
        id:"26",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"ngọt đắng cuộc đời",
         img:"https://tse3.mm.bing.net/th?id=OIP.2tJJeMfqNdhjhHjZ8h7nJQHaEK&pid=Api&P=0&h=220",
        
     },
    {
        id:"27",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"vô danh",
        img:"https://tse2.mm.bing.net/th?id=OIP.shyFL9DnMULq2EU8bnIucQHaEK&pid=Api&P=0&h=220",
        
    },
    {
        id:"28",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"thiên đàng hay địa ngục",
        img:"https://tse4.mm.bing.net/th?id=OIP.0WmYhS120c-2AT5eKZ6ZBAHaEK&pid=Api&P=0&h=220",
        
    },
    {
        id:"29",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"long mã tinh thần",
        img:"https://tse2.mm.bing.net/th?id=OIP.EPE8vhjpZpxOGcTbF0gzqgHaEK&pid=Api&P=0&h=220",
        
    },
    {
        id:"30",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"thời địa của ta",
        img:"https://tse1.mm.bing.net/th?id=OIP.kmrddIHgEtX-5G99UtnPlAHaEB&pid=Api&P=0&h=220",
        
    },
    {
        id:"31",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Indiana Jones và vòng quay định mệnh ",
        img:"https://tse4.mm.bing.net/th?id=OIP.s0Ar-hv3_3akEWSOxjyfzwHaEK&pid=Api&P=0&h=220",
        
    },
    {
        id:"32",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"đấu phá thương khung ",
        img:"https://tse1.mm.bing.net/th?id=OIP.okamh02XxqZPVMYyjb77GQHaEL&pid=Api&P=0&h=220",
        
    },
    {
        id:"33",
        statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"one piece",
        img:"https://tse4.mm.bing.net/th?id=OIP.SYpeQIglzSOOegO5OLf9nwHaEM&pid=Api&P=0&h=220",
        
    },
    {
        id:"34",
        statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Naruto",
        img:"https://tse3.mm.bing.net/th?id=OIP.8kBolo6yE8Ntbf6BGcZ-hAHaEo&pid=Api&P=0&h=220",
        
    },
    {
        id:"35",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Boruto",
        img:"https://tse1.mm.bing.net/th?id=OIP.IOwn7T0Nzv6fPzccJ3K6PgHaFj&pid=Api&P=0&h=220",
        
    },
    {
        id:"36",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"7 viên ngọc rồng",
        img:"https://tse4.mm.bing.net/th?id=OIP.SMqlplw3LmkVIpLvqmzfmgHaFj&pid=Api&P=0&h=220",
        
    },
    {
        id:"37",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"Đo Re Mon",
         img:"https://tse3.mm.bing.net/th?id=OIP.yo2WSC0ZIQBizf2bC17bwAHaFj&pid=Api&P=0&h=220",
        
     },
    {
        id:"38",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"chiếc bất lửa và váy công chúa",
        img:"https://tungtang.com.vn/blog/wp-content/uploads/2022/11/chiec-bat-lua-va-chiec-vay-cong-chua-tung-tang.jpeg",
        
    },
    {
        id:"39",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"bạch phát vương phi ",
        img:"https://static2.vieon.vn/vieplay-image/thumbnail_v4/2020/12/27/e4gb65hm_1920x1080-bachphatvuongphi5e678e457343568d17a031612929538a.jpg",
        
    },
    {
        id:"40",
        statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"vân tịch truyện ",
        img:"https://tse1.mm.bing.net/th?id=OIP.vddn_ekY4DF8T2M_0_RJIAHaKY&pid=Api&P=0&h=220",
        
    },
    {
        id:"41",
        statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"spiderman",
        img:"https://tse4.mm.bing.net/th?id=OIP.02_xra9QDLDvrzOLzrrrHAHaEK&pid=Api&P=0&h=220",
        
    },
    {
        id:"42",
         statuss:"đã kết thúc",
        year:"2012",
        type:"phim chiến dấu", 
        time:"132 phút",
        paramater:"layout, passenger",
        country:"phim pháp",
        times:"1 tập",
        director:"luffy,nmai,ussop",
        titleExtra:"THE WHITE STORM 3: HEAVEN OR HELL (2023)",
        title:"đấu phá thương khung ",
        img:"https://tse1.mm.bing.net/th?id=OIP.okamh02XxqZPVMYyjb77GQHaEL&pid=Api&P=0&h=220",
        
    },
]